### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by julienmarie** [lfyzjck/phabricator-alfred#1]
Hello,

I get this error

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "phapi.py", line 8, in <module>
    ph = Phabricator()
  File "phabricator/__init__.py", line 302, in __init__
    self.username = username if username else ARCRC['hosts'][self.host]['user']
```

It seems to be looking for a user name, but arcanist just sets up a conduit token. What is the proper way to install it? ( some instructions in the readme would be nice :) )

**Comment by lfyzjck** [comment]
Thanks for your reply.
Just follow this guide and install Arcanist which is a CLI tools for Phabricator:

https://secure.phabricator.com/book/phabricator/article/arcanist/

Specify the settings in `~/.arcrc` (JSON) through the config key. This file can be modified also by `arc set-config --global`

**Comment by julienmarie** [comment]
I got it working thanks :) no direct post of tasks? Just redirect to browser?

Envoyé via Outlook Mobile

On Thu, Jan 14, 2016 at 7:08 PM -0800, "lfyzjck" notifications@github.com wrote:

Thanks for your reply.

Just follow this guide and install Arcanist which is a CLI tools for Phabricator:

https://secure.phabricator.com/book/phabricator/article/arcanist/

Specify the settings in ~/.arcrc (JSON) through the config key. This file can be modified also by arc set-config --global

**Comment by lfyzjck** [comment]
This is just a toy tools.
If you need more feature, you can submit a pull request or just tell me what you needed, i will implement it later. :)
